# IMPORTANT: If using any theme, with SCSS files, you MUST use hugo-extended
# otherwise you will spend an hour wondering why you cannot change any colours..
# while hugo itself says /nothing/ about being unable to do sh*t for you. Grr :(
# https://gohugo.io/troubleshooting/faq/

languageCode = "en-us"
title = "(Ashbysoft *)"
baseurl = "https://phil.ashbysoft.com/www.ashbysoft.com/"
theme = "m10c"

cleandestinationdir = true
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "about"
    title = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "articles"
    title = "Articles"
    url = "/articles/"

  [[menu.main]]
    identifier = "posts"
    title = "Blog"
    url = "/posts/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "Phil & Stu"
  description = "The home of Ashbysoft."
  [params.style]
    darkestColor = "#002255"
    darkColor = "#1d3159"
    lightColor = "#a6bbe5"
    lightestColor = "#fad07f"
    primaryColor = "#ac853b"
