backend:
   name: github
   branch: master
   repo: phlash/www.ashbysoft.com
   base_url: https://phil.ashbysoft.com

publish_mode: editorial_workflow
media_folder: "static/images/upload"
public_folder: "/images/upload"

collections:
   - name: "posts"
     label: "Posts"
     folder: "content/posts"
     create: true
     slug: "{{slug}}"
     identifier_field: "title"
     fields:
        - { name: "title", label: "Title", widget: "string" }
        - { name: "summary", label: "Summary", widget: "markdown" }
        - { name: "date", label: "Published", widget: "datetime" }
        - { name: "body", label: "Body", widget: "markdown" }

   - name: "articles"
     label: "Articles"
     folder: "content/articles"
     create: true
     slug: "{{slug}}"
     identifier_field: "title"
     fields:
        - { name: "title", label: "Title", widget: "string" }
        - { name: "summary", label: "Summary", widget: "markdown" }
        - { name: "date", label: "Published", widget: "datetime" }
        - { name: "body", label: "Body", widget: "markdown" }
