backend:
   name: github
   branch: master
   repo: phlash/hugo-test
   base_url: https://phil.ashbysoft.com

publish_mode: editorial_workflow
media_folder: "static/images/upload"
public_folder: "/images/upload"

collections:
  - name: "posts"
    label: "Post"
    folder: "content/posts"
    fields:
            - name: "title"
              label: "Title"
              widget: "string"
