backend:
   name: github
   branch: master
   repo: phlash/hugo-test
   base_url: https://phil.ashbysoft.com

publish_mode: editorial_workflow
media_folder: "static/images/upload"
public_folder: "/hugo-test/images/upload"

collections:
  - name: "posts"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
            - { name: "title", label: "Title", widget: "string" }
            - { name: "date", label: "Published", widget: "datetime" }
            - { name: "body", label: "Body", widget: "markdown" }
